from binarytree import Node

root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.right.left = Node(5)
root.right.right = Node(6)
root.left.left.left = Node(3)
root.left.left.right = Node(5)
root.right.right.left = Node(5)
root.right.left.left = Node(3)
root.right.left.right = Node(7)
root.right.right.right = Node(6)
# root.left.right.right = Node(6)
# show(root)
print(root)
